name: Dismine
version: '${project.version}'
main: de.creelone.dismine.Dismine
api-version: 1.19
load: STARTUP
authors: [cfp, j0code]
website: https://github.com/creelonestudios/Dismine
database: true

commands:
  shrug:
    description: "¯\_(ツ)_/¯"
  tableflip:
    description: "(╯°□°）╯︵ ┻━┻"
  unflip:
    description: "┬─┬ ノ( ゜-゜ノ)"
  doubleflip:
    description: "┻━┻彡 ヽ(ಠ益ಠ)ノ彡┻━┻"
  owo:
    description: "\\(OwO)/"
  sync:
    description: "Sync with your discord account"
  nick:
    description: "Change your nickname"
  feed:
    description: "Feed a player"
  heal:
    description: "Heal a player"
  gm:
    description: "Change your gamemode"
  speed:
    description: "Change your speed"
  flyspeed:
    description: "Change your flying speed"
  walkspeed:
    description: "Change your walking speed"
  fly:
    description: "Toggle flying"
  warp:
    description: "Teleport to a warp"
  home:
    description: "Teleport to your home"
  sethome:
    description: "Set your home"
  homes:
    description: "List your homes"
  delhome:
    description: "Delete your home"
  setwarp:
    description: "Set a warp"
  delwarp:
    description: "Delete a warp"
  vanish:
    description: "Toggle vanish"
  godmode:
    description: "Toggle god mode"
    aliases: [godm]